language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - "pip install -r requirements.txt"
script:
  - ./manage.py test
branches:
  only:
  - develop
  - feature/integrate-coveralls
env:
  global:
    - TRAVIS_BUILD=true
after_success:
    - coveralls
